apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  selector: {app: exercise-3}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
