apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {app: {{ .Chart.Name }}}
  template:
    metadata:
      labels: {app: {{ .Chart.Name }}}
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - {name: http, containerPort: 80}
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-credentials
                  key: API_KEY
          resources:
            requests: {cpu: 10m, memory: 16Mi}
            limits: {memory: 64Mi}
